// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace api.Migrations
{
    [DbContext(typeof(RoomMateDbContext))]
    [Migration("20190501052331_initial4")]
    partial class initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<int>("HouseId");

                    b.Property<string>("State");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("HouseId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("DueDate");

                    b.HasKey("Id");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("api.Features.House.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("RentId");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("api.RoomMate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<int?>("HouseId");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("RoomMates");
                });

            modelBuilder.Entity("Address", b =>
                {
                    b.HasOne("api.Features.House.House", "House")
                        .WithOne("Address")
                        .HasForeignKey("Address", "HouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api.Features.House.House", b =>
                {
                    b.HasOne("Bill", "Rent")
                        .WithMany()
                        .HasForeignKey("RentId");
                });

            modelBuilder.Entity("api.RoomMate", b =>
                {
                    b.HasOne("api.Features.House.House")
                        .WithMany("RoomMates")
                        .HasForeignKey("HouseId");
                });
#pragma warning restore 612, 618
        }
    }
}
